[platformio]
default_envs = teensy41_stage0

[env:teensy41_stage0]
platform = teensy
board = teensy41
framework = arduino
monitor_speed = 115200
lib_deps =
    https://github.com/tonton81/FlexCAN_T4.git#b928bcb2f74fdf0ccb76660f52ca1a2819ff4e2c
    https://github.com/adafruit/Adafruit_BNO08x.git#34d977bbb560b54e60d64bc1c946ea9af46511ea
build_flags =
    -D BENI_STAGE0_ENABLE_IMU=1
    -D BENI_STAGE0_CAN_INTERNAL_LOOPBACK=1
    -Wall
    -Wextra
