#!/usr/bin/env python3
"""Generate r2a_knee_linkage_table.h from r2a_calc.py's solver.

The table and the closed form in r2a_knee_linkage.h must agree; the host test
(test_linkage.cpp) checks that.  Rerun this after any linkage change:

    python3 firmware/r2a/gen_linkage_table.py
"""
import json
import math
import os
import sys

import numpy as np

HERE = os.path.dirname(os.path.abspath(__file__))
sys.path.insert(0, os.path.join(HERE, '..', '..'))
import r2a_calc as c  # noqa: E402

A, B, CL, DEL = 32.0, 120.0, 30.0, -12.0
alphas = np.arange(48.0, 153.0 + 1e-9, 1.0)
r = c.solve_linkage(alphas, A, B, CL, DEL, 1)
g = c.FUSION
rows = []
for i, a in enumerate(alphas):
    rows.append((a, math.degrees(r['th_c'][i]), float(r['n'][i]), float(r['mu'][i])))
stop_f = g['stops']['flex']['contact_deg']
stop_e = g['stops']['ext']['contact_deg']
out = ['// Generated by gen_linkage_table.py from r2a_calc.solve_linkage(); do not edit.',
       '// Fusion %s v%d: stops %.2f / %.2f deg.' % (g['document'], g['version'], stop_f, stop_e),
       '#pragma once', '', 'namespace beni::r2a {', '',
       'struct KneeMapRow { float alpha_deg; float theta_c_deg; float ratio_n; float mu_deg; };', '',
       'constexpr float kTableAlpha0Deg = %.1ff;' % alphas[0],
       'constexpr float kTableStepDeg = 1.0f;',
       'constexpr int kTableRows = %d;' % len(rows),
       'constexpr KneeMapRow kKneeMap[kTableRows] = {']
for a, t, n, m in rows:
    out.append('    {%.1ff, %.4ff, %.5ff, %.3ff},' % (a, t, n, m))
out += ['};', '', '}  // namespace beni::r2a', '']
open(os.path.join(HERE, 'r2a_knee_linkage_table.h'), 'w').write('\n'.join(out))
print('wrote %d rows, stops %.2f / %.2f' % (len(rows), stop_f, stop_e))
